Improve pushing out tags
legalthings/mustache-tidy pull request #10
Opened 2017-02-17 19:11 UTC by Minstel

Depends on PR https://github.com/legalthings/mustache-tidy/pull/9

2017-02-23 05:21 UTC, jasny requested changes
You need to do `Improve tags` before `Fix for tables`. Now, step 5 will actually break the thing you just fixed in step 4.

2017-02-23 05:53 UTC, Minstel commented
No, it wont. 5 step does not push tags out of table cells

2017-02-23 06:13 UTC, jasny commented
That is equally bad. Example:

```
<table>
  <tr>
     <td>{{foo}}hello</td>
     <td>world</td>
  </tr>
  <tr>
     <td>goodbye</td>
     <td>moon{{/foo}}</td>
  </tr>
</table>
```

will become 

```
<table>
  {{foo}}
  <tr>
     <td>hello</td>
     <td>world</td>
  </tr>
  <tr>
     <td>goodbye</td>
     <td>moon</td>
  </tr>
  {{/foo}}
</table>
```

Than it needs to push out, to become 

```
{{foo}}
<table>
  <tr>
     <td>hello</td>
     <td>world</td>
  </tr>
  <tr>
     <td>goodbye</td>
     <td>moon</td>
  </tr>
</table>
{{/foo}}
```

**NOT**

```
<table>
  <tr>
     <td>{{foo}}hello{{/foo}}</td>
     <td>{{foo}}world{{/foo}}</td>
  </tr>
  <tr>
     <td>{{foo}}goodbye{{/foo}}</td>
     <td>{{foo}}moon{{/foo}}</td>
  </tr>
</table>
```

2017-03-09 14:02 UTC, jasny approved these changes

2017-03-09 14:03 UTC, merged