Module for replacing empty nodes by containing tags
legalthings/mustache-tidy pull request #4
Opened 2017-02-09 16:02 UTC by Minstel

2017-02-09 23:34 UTC, jasny requested changes

2017-02-09 23:34 UTC, jasny commented on spec/replace-empty-node-spec.js
> +describe('Replacing empty dom nodes with containing tags', function() {
Please also add tests for common cases

```html
<p>{{#tag}}</p>
<p>Hello world</p>
<p>{{/tag}}</p>
```

should become `{{#tag}}<p>Hello world</p>{{/tag}}`

and 

```html
<p>{{#tag}}</p>
<p>Hello world</p>
<p>{{/tag}} {{^tag}}</p>
<p>Good night</p>
<p>{{/tag}}</p>
```
should become `{{#tag}}<p>Hello world</p>{{/tag}} {{^tag}}<p>Good night</p>{{/tag}}`

2017-02-09 23:34 UTC, jasny commented on scripts/utils.js
> +var Node = require('../node_modules/jsdom/lib/jsdom/living/generated/Node.js');
Can't you use `require('jsdom/lib/jsdom/living/generated/Node.js')`?

2017-02-10 10:26 UTC, Minstel commented
```
<p>{{#tag}}</p>
<p>Hello world</p>
<p>{{/tag}} {{^tag}}</p>
<p>Good night</p>
<p>{{/tag}}</p>
```

To correctly handle `<p>{{/tag}} {{^tag}}</p>`, second step (moving tags) is required, when closing tag is first moved out of node. Currently replacing nodes hanles the following cases: 

- `<p>{{#tag}}</p>`
- `<p>{{/tag}}</p>`
- <p>{{^tag}} {{/tag}}</p>

This is related to current algo - while handling current section, it does not look for sibling tags (for better performance), and just consideres them as some data.
I did corresponding change to readme.

2017-02-10 14:07 UTC, jasny commented
@Minstel You should treat `{{^tag}}` exactly the same as `{{#tag}}`. A `^` just means 'not'.

If a `<p>` contains only start and/or end tags, than remove `<p>`. It doesn't order or number of start tags doesn't matter. Doing step 2 without removing this, means we'll end up with empty paragraphs.

2017-02-10 16:50 UTC, merged